-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 20:29:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas` DEFAULT CHARACTER SET utf8 ;
USE `vendas` ;

-- -----------------------------------------------------
-- Table `vendas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas`.`cliente` (
  `id` INT GENERATED ALWAYS AS (0) VIRTUAL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `rg_ie` VARCHAR(45) NOT NULL,
  `nome_razao` VARCHAR(45) NOT NULL,
  `cep_cliente` VARCHAR(9) NOT NULL,
  `numero_residencia` INT NOT NULL,
  `telefones_cliente` VARCHAR(255) NOT NULL,
  `emails_cliente` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`cpf_cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas`.`produtos` (
  `id_produtos` INT GENERATED ALWAYS AS (0) VIRTUAL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `descricao_produto` VARCHAR(300) NOT NULL,
  `valor_unitario` DECIMAL(8,2) UNSIGNED NOT NULL,
  `percentual_icms` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `forma_pgto` ENUM('pix', 'boleto', 'crédito', 'débito', 'dinheiro') NOT NULL,
  `valor_desconto` DECIMAL(8,2) NOT NULL,
  `valor_total` DECIMAL(8,2) NOT NULL,
  `cep_entrega` VARCHAR(45) NOT NULL,
  `num_residencia` INT NOT NULL,
  `cliente_cpf_cnpj` VARCHAR(45) NOT NULL,
  `credito_pre` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id_venda`, `cliente_cpf_cnpj`),
  INDEX `fk_venda_cliente_idx` (`cliente_cpf_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`cliente_cpf_cnpj`)
    REFERENCES `vendas`.`cliente` (`cpf_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendas`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas`.`venda_produto` (
  `venda_id_venda` INT NOT NULL,
  `venda_cliente_cpf_cnpj` VARCHAR(45) NOT NULL,
  `produtos_id_produtos` INT NOT NULL,
  `quantidade_produto` INT NOT NULL,
  PRIMARY KEY (`venda_id_venda`, `venda_cliente_cpf_cnpj`, `produtos_id_produtos`),
  INDEX `fk_venda_has_produtos_produtos1_idx` (`produtos_id_produtos` ASC) VISIBLE,
  INDEX `fk_venda_has_produtos_venda1_idx` (`venda_id_venda` ASC, `venda_cliente_cpf_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_produtos_venda1`
    FOREIGN KEY (`venda_id_venda` , `venda_cliente_cpf_cnpj`)
    REFERENCES `vendas`.`venda` (`id_venda` , `cliente_cpf_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id_produtos`)
    REFERENCES `vendas`.`produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
